# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=128)),
                ('otwarte_od', models.CharField(max_length=5)),
                ('otwarte_do', models.CharField(max_length=5)),
                ('adres', models.CharField(max_length=128)),
                ('telefon', models.CharField(max_length=9)),
            ],
        ),
    ]
