# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='otwarte_do',
            field=models.SmallIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='otwarte_od',
            field=models.SmallIntegerField(max_length=5),
        ),
    ]
